import { rgba } from 'polished'

export const themeColors = {
  light: {
    app: {
      headerToggleColor: '#4db380',
      appSecondaryColor: '#cbe8d9',
      sidebarBGColor: '#575757',
      sidebarFillColor: '#dee3e5',
      paperColor: '#eeeeee',
    },
    torrentCard: {
      accentCardColor: '#337a57',
      sectionLabelColor: 'rgba(0, 0, 0, 0.72)',
      buttonBGColor: rgba('#337a57', 0.5),
      cardPrimaryColor: '#00a572',
      cardSecondaryColor: '#74c39c',
    },
    dialogTorrentDetailsContent: {
      posterBGColor: '#74c39c',
      gradientStartColor: '#e4f6ed',
      gradientEndColor: '#b5dec9',
      cacheSectionBGColor: '#a8d4be',
      widgetFontColor: '#fff',
      titleFontColor: '#000',
      subNameFontColor: '#7c7b7c',
      torrentFilesSectionBGColor: '#f1eff3',
      bufferTrailStartColor: '#c5e6d4',
      bufferTrailEndColor: '#b5dec9',
      bufferEmptyTrackColor: '#e8f5ef',
      bufferTrackBorderColor: '#337a57',
    },
    detailedView: {
      gradientStartColor: '#e4f6ed',
      gradientEndColor: '#b5dec9',
      cacheSectionBGColor: '#fff',
    },
    addDialog: {
      gradientStartColor: '#e4f6ed',
      gradientEndColor: '#b5dec9',
      fontColor: '#000',
      notificationErrorBGColor: '#cda184',
      notificationSuccessBGColor: '#88cdaa',
      languageSwitchBGColor: '#74c39c',
      languageSwitchFontColor: '#e4f6ed',
      posterBGColor: '#74c39c',
      separatorColor: 'rgba(0, 0, 0, 0.12)',
      dropzoneBorderColor: 'rgba(0, 0, 0, 0.1)',
      dropzoneHoverBGColor: 'rgba(0, 0, 0, 0.04)',
    },
    torrentFunctions: {
      fontColor: '#000',
    },
    table: {
      defaultPrimaryColor: '#009879',
      defaultSecondaryColor: '#00a383',
      defaultTertiaryColor: '#03aa89',
      rowBGColor: '#f3f3f3',
      viewedRowBGColor: '#ddd',
      dividerColor: '#d2d2d2',
      rowFontColor: '#000',
      shortTableButtonsBGColor: '#f3f3f3',
      viewedPrimaryColor: '#858c90',
      viewedSecondaryColor: '#8c9498',
      viewedTertiaryColor: '#949ca0',
    },
    settingsDialog: {
      contentBG: '#f1eff3',
      footerBG: '#fff',
      cacheBeforeReaderColor: '#b3dfc9',
      cacheAfterReaderColor: '#00a572',
      preloadCacheBorderColor: '#323637',
      preloadCacheFontColor: '#000',
      storageSelectedBG: '#323637',
      storageUnselectedBG: '#dee3e5',
      storageSelectedIcon: '#dee3e5',
      storageUnselectedIcon: '#323637',
    },
  },
  dark: {
    app: {
      headerToggleColor: '#3d7a5c',
      appSecondaryColor: '#1e2824',
      sidebarBGColor: '#161c1a',
      sidebarFillColor: '#c5d4cc',
      paperColor: '#242e2a',
    },
    torrentCard: {
      accentCardColor: '#2f6b4f',
      sectionLabelColor: 'rgba(255, 255, 255, 0.72)',
      buttonBGColor: rgba('#1a3d2e', 0.92),
      cardPrimaryColor: '#1b4d3a',
      cardSecondaryColor: '#2a5f49',
    },
    dialogTorrentDetailsContent: {
      posterBGColor: '#2a5f49',
      gradientStartColor: '#24352e',
      gradientEndColor: '#1e2824',
      cacheSectionBGColor: '#24352e',
      widgetFontColor: rgba('#fff', 0.85),
      titleFontColor: '#f1eff3',
      subNameFontColor: '#b7c9c0',
      torrentFilesSectionBGColor: rgba('#1e2824', 0.95),
      bufferTrailStartColor: '#2a5f49',
      bufferTrailEndColor: '#1b4d3a',
      bufferEmptyTrackColor: '#2f3d38',
      bufferTrackBorderColor: '#4db380',
    },
    detailedView: {
      gradientStartColor: '#24352e',
      gradientEndColor: '#1e2824',
      cacheSectionBGColor: '#2a5f49',
    },
    addDialog: {
      gradientStartColor: '#24352e',
      gradientEndColor: '#1e2824',
      fontColor: '#fff',
      notificationErrorBGColor: '#c82e3f',
      notificationSuccessBGColor: '#1b4d3a',
      languageSwitchBGColor: '#2a5f49',
      languageSwitchFontColor: '#e4f6ed',
      posterBGColor: '#2a5f49',
      separatorColor: 'rgba(255, 255, 255, 0.12)',
      dropzoneBorderColor: 'rgba(255, 255, 255, 0.2)',
      dropzoneHoverBGColor: 'rgba(255, 255, 255, 0.06)',
    },
    torrentFunctions: {
      fontColor: '#f1eff3',
    },
    table: {
      defaultPrimaryColor: '#1b4d3a',
      defaultSecondaryColor: '#2a5f49',
      defaultTertiaryColor: '#347a5c',
      rowBGColor: '#24352e',
      viewedRowBGColor: '#2f3d38',
      dividerColor: '#3a4a43',
      rowFontColor: '#f1eff3',
      shortTableButtonsBGColor: '#24352e',
      viewedPrimaryColor: '#5a6b64',
      viewedSecondaryColor: '#65756e',
      viewedTertiaryColor: '#708078',
    },
    settingsDialog: {
      contentBG: '#24352e',
      footerBG: '#1a221f',
      cacheBeforeReaderColor: '#3d7a5c',
      cacheAfterReaderColor: '#5ecf9a',
      preloadCacheBorderColor: '#c5d4cc',
      preloadCacheFontColor: '#f1eff3',
      storageSelectedBG: '#0f2a1f',
      storageUnselectedBG: '#3a4a43',
      storageSelectedIcon: '#c5d4cc',
      storageUnselectedIcon: '#e8f0ec',
    },
  },
}

export const mainColors = {
  light: {
    primary: '#00875a',
    secondary: '#00a572',
    labels: rgba('#000', 0.9),
  },
  dark: {
    primary: '#4db380',
    secondary: '#5ecf9a',
    labels: rgba('#fff', 0.9),
  },
}
