import { alphaCss } from './color'

export const themeColors = {
  light: {
    app: {
      headerToggleColor: '#4db380',
      appSecondaryColor: '#cbe8d9',
      sidebarBGColor: '#575757',
      sidebarFillColor: '#dee3e5',
      paperColor: '#eeeeee',
    },
    torrentCard: {
      accentCardColor: '#337a57',
      buttonBGColor: alphaCss('#337a57', 0.5),
      cardPrimaryColor: '#00a572',
      cardSecondaryColor: '#74c39c',
    },
    dialogTorrentDetailsContent: {
      posterBGColor: '#74c39c',
      gradientStartColor: '#e4f6ed',
      gradientEndColor: '#b5dec9',
      cacheSectionBGColor: '#88cdaa',
      widgetFontColor: '#fff',
      titleFontColor: '#000',
      subNameFontColor: '#7c7b7c',
      torrentFilesSectionBGColor: '#f1eff3',
      bufferTrailStartColor: '#c5e6d4',
      bufferTrailEndColor: '#b5dec9',
      bufferEmptyTrackColor: '#e8f5ef',
      bufferTrackBorderColor: '#337a57',
    },
    detailedView: {
      gradientStartColor: '#e4f6ed',
      gradientEndColor: '#b5dec9',
      cacheSectionBGColor: '#fff',
    },
    addDialog: {
      gradientStartColor: '#e4f6ed',
      gradientEndColor: '#b5dec9',
      fontColor: '#000',
      notificationErrorBGColor: '#cda184',
      notificationSuccessBGColor: '#88cdaa',
      languageSwitchBGColor: '#74c39c',
      languageSwitchFontColor: '#e4f6ed',
      posterBGColor: '#74c39c',
      separatorColor: 'rgba(0, 0, 0, 0.12)',
      dropzoneBorderColor: 'rgba(0, 0, 0, 0.1)',
      dropzoneHoverBGColor: 'rgba(0, 0, 0, 0.04)',
    },
    torrentFunctions: {
      fontColor: '#000',
    },
    table: {
      defaultPrimaryColor: '#009879',
      defaultSecondaryColor: '#00a383',
      defaultTertiaryColor: '#03aa89',
      rowBGColor: '#f3f3f3',
      viewedRowBGColor: '#ddd',
      dividerColor: '#d2d2d2',
      rowFontColor: '#000',
      shortTableButtonsBGColor: '#f3f3f3',
      outlinedButtonBorderColor: 'rgba(0, 152, 121, 0.45)',
      viewedPrimaryColor: '#858c90',
      viewedSecondaryColor: '#8c9498',
      viewedTertiaryColor: '#949ca0',
    },
    settingsDialog: {
      contentBG: '#f1eff3',
      footerBG: '#fff',
      separatorColor: 'rgba(0, 0, 0, 0.12)',
      cacheBeforeReaderColor: '#b3dfc9',
      cacheAfterReaderColor: '#00a572',
      preloadCacheBorderColor: '#323637',
      preloadCacheFontColor: '#000',
      storageSelectedBG: '#323637',
      storageUnselectedBG: '#dee3e5',
      storageSelectedIcon: '#dee3e5',
      storageUnselectedIcon: '#323637',
    },
    aboutDialog: {
      bandBG: '#e8e5eb',
      bandFontColor: '#323637',
    },
  },
  dark: {
    app: {
      headerToggleColor: '#545a5e',
      appSecondaryColor: '#545a5e',
      sidebarBGColor: '#323637',
      sidebarFillColor: '#dee3e5',
      paperColor: '#323637',
    },
    torrentCard: {
      accentCardColor: '#323637',
      buttonBGColor: alphaCss('#323637', 0.5),
      cardPrimaryColor: '#545a5e',
      cardSecondaryColor: alphaCss('#dee3e5', 0.4),
    },
    dialogTorrentDetailsContent: {
      posterBGColor: alphaCss('#dee3e5', 0.4),
      gradientStartColor: '#656f76',
      gradientEndColor: '#545a5e',
      cacheSectionBGColor: '#3c4244',
      widgetFontColor: alphaCss('#fff', 0.8),
      titleFontColor: '#f1eff3',
      subNameFontColor: '#dee3e5',
      torrentFilesSectionBGColor: alphaCss('#545a5e', 0.9),
      bufferTrailStartColor: '#5a6166',
      bufferTrailEndColor: '#656f76',
      bufferEmptyTrackColor: '#3c4244',
      bufferTrackBorderColor: '#949ca0',
    },
    detailedView: {
      gradientStartColor: '#656f76',
      gradientEndColor: '#545a5e',
      cacheSectionBGColor: '#949ca0',
    },
    addDialog: {
      gradientStartColor: '#656f76',
      gradientEndColor: '#545a5e',
      fontColor: '#fff',
      notificationErrorBGColor: '#c82e3f',
      notificationSuccessBGColor: '#323637',
      languageSwitchBGColor: '#545a5e',
      languageSwitchFontColor: '#dee3e5',
      posterBGColor: '#dee3e5',
      separatorColor: 'rgba(255, 255, 255, 0.12)',
      dropzoneBorderColor: 'rgba(255, 255, 255, 0.2)',
      dropzoneHoverBGColor: 'rgba(255, 255, 255, 0.06)',
    },
    torrentFunctions: {
      fontColor: '#f1eff3',
    },
    table: {
      defaultPrimaryColor: '#323637',
      defaultSecondaryColor: alphaCss('#545a5e', 0.9),
      defaultTertiaryColor: '#545a5e',
      rowBGColor: alphaCss('#545a5e', 0.35),
      viewedRowBGColor: alphaCss('#545a5e', 0.55),
      dividerColor: '#656f76',
      rowFontColor: '#f1eff3',
      shortTableButtonsBGColor: alphaCss('#545a5e', 0.35),
      outlinedButtonBorderColor: alphaCss('#dee3e5', 0.45),
      viewedPrimaryColor: '#5a6166',
      viewedSecondaryColor: '#656f76',
      viewedTertiaryColor: '#707880',
    },
    settingsDialog: {
      contentBG: '#5a6166',
      footerBG: '#323637',
      separatorColor: 'rgba(255, 255, 255, 0.12)',
      cacheBeforeReaderColor: '#656f76',
      cacheAfterReaderColor: '#949ca0',
      preloadCacheBorderColor: '#dee3e5',
      preloadCacheFontColor: '#f1eff3',
      storageSelectedBG: '#323637',
      storageUnselectedBG: alphaCss('#545a5e', 0.9),
      storageSelectedIcon: '#dee3e5',
      storageUnselectedIcon: '#323637',
    },
    aboutDialog: {
      bandBG: '#3c4244',
      bandFontColor: '#f1eff3',
    },
  },
}

export const mainColors = {
  light: {
    primary: '#00a572',
    secondary: '#00a572',
    labels: alphaCss('#000', 0.9),
  },
  dark: {
    primary: '#323637',
    secondary: '#dee3e5',
    labels: alphaCss('#fff', 0.9),
  },
}
